### ISSUE TITLE
KeyError: '[PICKUP]'

### ISSUE THREAD

**Issue by lisaalaz** [Ber666/ToolkenGPT#18]
Hi, 

when running eval on vh it seems that there are some tools in the test set that are not in the provided func_dict (for example I get a failure because of the missing [PICKUP] tool).

Could you update func_dict to include all the tools needed for the eval, and were these tools that are now missing in the repo used in training your model?

Many thanks!

**Comment by lisaalaz** [comment]
Hi, congrats @Ber666 on the great presentation at NeurIPS last week! I was wondering if you may have time to follow up on the above issue? Is this just an easy-to-fix bug in func_dict that is missing some of the tools then? Many thanks!

**Comment by Ber666** [comment]
Hi Lisa, sorry for the late response. I will try to look into it asap

**Comment by Ber666** [comment]
Hi, I checked the func_dict I use and it indeed doesn't include `[PICKUP]`. I looked into the training set and there are not any `[PICKUP]` actions either. Could you provide me with more information, like where will the error be thrown?

**Comment by lisaalaz** [comment]
Hi, thanks! So I have not finetuned this model myself, I am just running inference with the VH checkpoint you provide at https://drive.google.com/file/d/1hHBpy1Oqc1xEd2iQAtSlyi1KCtNFBzIn/view.
When I run inference, at example 20/50 it seems to attempt to call a [PICKUP] function, at which point it throws an error as this function is not in func_dict. Please see below:
<img width="820" alt="Screenshot 2023-12-22 at 19 05 40" src="https://github.com/Ber666/ToolkenGPT/assets/89645136/10b655d2-dfd9-4217-8cb3-9b82f9250e00">

**Comment by Ber666** [comment]
Hi, I just ran the experiments again and couldn't replicate the error message... Could you double check if your code is consistent to the latest version in this repo? In your error message it seems the line 468 of `model.py` is `func_id = self.func_dict[func]`, which is not the same as [model.py](https://github.com/Ber666/ToolkenGPT/blob/main/llama/model.py) in our repo.

Looking into the code, I also have no clues why `[PICKUP]` would appear there. In the line 468 you showed, the `func` should be an item in the discarded function set, which is preprocessed [here](https://github.com/Ber666/ToolkenGPT/blob/32201bdd05f87efddef9aebe88a74114c0526bd6/inference_llama.py#L133C22-L133C101). These discarded functions are also from `func_dict`, but we know `[PICKUP]` is not in the `func_dict`, so that's really confusing...

<img width="1290" alt="image" src="https://github.com/Ber666/ToolkenGPT/assets/46735523/69553e38-da09-4d29-94da-3611c53b50c6">

**Comment by lisaalaz** [comment]
Hi, thanks for the reply, I had just added some comments to your code for my own understanding, hence why the lines did not match. To be absolutely certain though, I re-cloned your repo today, re-downloaded the data, and reran the inference on this clean repo, but the issue is still there for me. This time I got an unrecognised function '[PET]' at example #41. I do load your checkpoint onto a LlaMA2 13B (I don't have access to LlaMA1, Meta is no longer responsive about the older models), so it's pretrained differently than LlaMA1. But of course I agree that it should not just be able to try to call functions that are not part of func_dict. Perhaps at some point you changed something in your code that may be causing this? Anyway I will try to find the cause too in the next days

**Comment by Ber666** [comment]
Hi, I believe the reason is that you used a different base model from the
one those embeddings are trained on. Somehow those special tokens are not
activated and those [PICKUP] and [PET] things are just plain text that
llama2 wants to predict (just like how ICL works). If this code is
compatible with llama2, could you try training the embeddings yourself on
llama2? It doesn’t take more computing resources than inference.

**Comment by lisaalaz** [comment]
I see. I assumed the architecture of Llama2 would work identically but that is indeed an assumption. I will finetune it then. I finetuned Llama2 for the other tasks without issue so it should work then. Thanks!
