### ISSUE TITLE
Can you share the code using 0-shot Chatgpt?

### ISSUE THREAD

**Issue by TreasureHunter** [Ber666/ToolkenGPT#20]
Hi, 

I'm interested in your great work! I'd like to reproduce your results for 0-shot Chatgpt on GSM8K-XL and FuncQA. Can you share the code? The paper only provides the prompt for 0-shot Chatgpt.

Thanks for your reply!

**Comment by Ber666** [comment]
Can you share the code? @Leolty

**Comment by Leolty** [comment]
Hi @TreasureHunter,

A few months ago, I used `gpt-3.5-turbo` with the following prompt setup for solving mathematical problems:

```python
system_prompt = "You are a mathematical problem solver."
prompt_prefix = "Solve the following math problem step by step, and then provide the final answer in the format: 'So, the answer is xxx.'\n\n"
prompt = prompt_prefix + question
```

Since it's been a while, I'm not certain if the model's performance remains unchanged. You might want to consider trying a newer version, like `gpt-3.5-turbo-1106`, for possibly improved results.

Hope this helps!

**Comment by TreasureHunter** [comment]
Thanks for your great help!
