### ISSUE TITLE
Experiment environment

### ISSUE THREAD

**Issue by passenger20** [Ber666/ToolkenGPT#3]
Hi, it's a quite interesting study. It would probably be helpful to include a requirements.txt file to specify the versions of all the packages used.

**Comment by Ber666** [comment]
Hi, thanks for your interest! The requirements are basically the same as the original LLaMA repo. I didn't include a requirement file because I find sometimes it leads to more troubles if users directly run `pip install -r requirements.txt`.. Once you can run the code in LLaMA repo, it should be fine to run our code.

**Comment by Ber666** [comment]
There could be some other minor packages needed, but their versions don't matter.
